config/routes.rb
Rails.application.routes.draw do

  default_url_options Rails.application.config.action_mailer.default_url_options

  resources :events do
    member do
      post 'close'
    end
  end

  resources :movies

  devise_for :users, controllers: { registrations: :registrations }

  root 'application#index'

  get 'admin' => 'application#admin'

  resources :users, only: [:index, :show, :destroy, :update]

  get 'invite' => 'invitation#index'
  post 'invite/email' => 'invitation#for_email'
  get 'invite/link' => 'invitation#generate_link'

  resources :votes, only: [:index, :create, :destroy] do
    member do
      post :up, :down
    end
  end
end

app/models/invitation.rb
require 'bcrypt'
require 'date'
require 'cgi'

class Invitation < ActiveRecord::Base
  belongs_to :user
  before_create :set_expiration_date, :set_hash

  def self.id_hash(user, email=nil)
    base = email if email
    base ||= user.id.to_s + Date.today.to_datetime.to_s
    BCrypt::Password.create(base).to_s
  end

  def is_valid?
    expiresAt > Date.today
  end

  def is_invalid?
    not is_valid?
  end

  def for_email!(email)
    self.id_hash = Invitation::id_hash(self.user, email)
    self
  end

  private
  def set_hash
    self.id_hash ||= Invitation::id_hash(self.user)
  end

  def set_expiration_date
    self.expiresAt = Date.today + 5
  end

end

app/controllers/invitation_controller.rb
class InvitationController < ApplicationController
  before_action :check_user

  def index
    InvitationHelper::remove_invalid!
  end


  def generate_link
    invitation = Invitation.create user: current_user
    render plain: "#{InvitationHelper::join_url}?invitation=#{invitation.id_hash}"
  end

  def for_email
    email = email_params['email']
    Invitation.new(user: current_user).for_email!(email).save!
    Notifier.been_invited(email, by: current_user).deliver
    render plain: "OK"
  end

  private
  def email_params
    params.permit(:email)
  end
end

app/helpers/invitation_helper.rb
module InvitationHelper
  class << self
    def remove_invalid!
      Invitation.all.select(&:is_invalid?).each(&:destroy)
    end

    def find_for_email email
      Invitation.all.select { |i| BCrypt::Password.new(i.id_hash) == email } || []
    end

    def find_for_hash hash
      Invitation.find_by(id_hash: hash) || []
    end

    def join_url
      Rails.application.routes.url_helpers.new_user_registration_url
    end
  end
end

app/views/invitation/index.html.haml
.form
  %div
    = link_to invite_link_path, id: "invitation-link", class: "vote_header" do
      %i.fa.fa-forward.fa-lg
        %span.clear-font with link
    .hidden#invitation-link-loading= render 'layouts/loading'
    .hidden#invitation-link-input
      %h2 Send this link to a friend:
      %textarea.link{readonly: true}
  %div
    = link_to invite_email_path, id: "invitation-email", class: "vote_header" do
      %i.fa.fa-forward.fa-lg
        %span.clear-font with email
    .hidden#invitation-email-loading= render 'layouts/loading'
    .hidden#invitation-email-input
      %h2 Enter email:
      %textarea.link
      %p.hidden Sent
      %button OK