config/routes.rb
Rails.application.routes.draw do

  default_url_options Rails.application.config.action_mailer.default_url_options

  resources :events do
    member do
      post 'close'
    end
  end

  resources :movies

  devise_for :users, controllers: { registrations: :registrations }

  root 'application#index'

  get 'admin' => 'application#admin'

  resources :users, only: [:index, :show, :destroy, :update]

  get 'invite' => 'invitation#index'
  post 'invite/email' => 'invitation#for_email'
  get 'invite/link' => 'invitation#generate_link'

  resources :votes, only: [:index, :create, :destroy] do
    member do
      post :up, :down
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :movie
  has_many :vote_options
  accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true

  def vote_open?
    movie.nil?
  end

  def vote_closed?
    not vote_open?
  end

  def set_winning_movie
    self.movie = vote_options.max_by(&:sum_of_votes).movie
    self.save!
  end

  def votes_for
    vote_options.map(&:votes_for).flatten
  end

  def user_voted
    votes_for.map(&:voter_id).uniq
  end
end

app/controllers/events_controller.rb
require 'date'

class EventsController < ApplicationController
  include ApplicationHelper
  before_action :set_event, only: [:show, :edit, :update, :destroy, :close]
  before_action :check_user
  before_action :check_admin, only: [:edit, :update, :destroy, :close]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with @event
  end

  def edit
  end

  def create
    @event = event_service.call EventForm.new(event_params)
    if @event.persisted?
      flash[:notice] = "Event created."
      respond_with(@event)
    else
      flash[:error] = "Event creation failed!"
      render new_event_path
    end
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  def close
    @event.set_winning_movie
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def param_date(date_params)
      year  = date_params["date(1i)"].to_i
      month = date_params["date(2i)"].to_i
      day   = date_params["date(3i)"].to_i
      begin
        Date.new year,month,day
      rescue
        false
      end
    end

    def event_params
      params[:event][:date] = param_date params[:event]
      params.require(:event).permit(:date, :movie_id, vote_options_attributes: [ :id, :_destroy, :movie_id])
    end

    def event_service
      @event_service ||= EventService.new
    end
end

app/helpers/events_helper.rb
module EventsHelper

  def votable_events
    Event.all.select(&:vote_open?)
  end
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .field.flex
    = f.label :date
    = ": "
    = f.date_select :date
  %h3 Vote
  #vote_options
    .exisiting
      = f.fields_for :vote_options do |vote_option|
        = render 'vote_option_fields', :f => vote_option
    .links
      = link_to_add_association f, :vote_options do
        %i.fa.fa-plus
  .actions
    = f.submit

app/views/events/_vote_option_fields.haml
.nested-fields.field.flex
  = link_to_remove_association f do
    %i.fa.fa-trash-o.red
  = f.label :movie
  = f.collection_select :movie_id, Movie.all, :id, :name, { include_blank: true }, class: 'select2'

app/views/events/edit.html.haml
.form
  = link_to events_path, class: "backward" do
    %i.fa.fa-backward.fa-2x
  %h1 Editing event
  = render 'form'
  = link_to 'Show', @event

app/views/events/index.html.haml
%h1 Listing events
- if current_user.try :admin?
  %p.float-right
    = link_to new_event_path do
      %i.fa.fa-plus.fa-2x
%table
  %thead
    %tr
      %th Date
      %th Movie
      %th Show
      - if current_user.try :admin?
        %th Edit
        %th Destroy
  %tbody
    - @events.each do |event|
      %tr
        %td= event.date
        %td= event.movie && (event.movie.name || event.movie.id ) || "-Under vote-"
        %td
          = link_to event do
            %i.fa.fa-search
        - if current_user.try :admin?
          %td
            = link_to edit_event_path(event) do
              %i.fa.fa-pencil-square-o.yellow
          %td
            = link_to event, method: :delete, data: { confirm: 'Are you sure?' } do
              %i.fa.fa-trash-o.red

app/views/events/new.html.haml
.form
  %h1 New event
  = render 'form'
  = link_to 'Back', events_path

app/views/events/show.html.haml
.form
  = link_to events_path, class: "backward" do
    %i.fa.fa-backward.fa-2x
  %p
    %strong Date:
    = @event.date
  - if @event.movie.nil?
    %p
      %strong Vote:
      - for vote_option in @event.vote_options
        %p
          - unless vote_option.movie.nil?
            = vote_option.movie.name
            \:
            = vote_option.votes_for.up.size - vote_option.votes_for.down.size
  - else
    %p
      %strong Movie:
      = @event.movie.name
  - if current_user.try :admin?
    = link_to 'Edit', edit_event_path(@event)