config/routes.rb
Rails.application.routes.draw do

  default_url_options Rails.application.config.action_mailer.default_url_options

  resources :events do
    member do
      post 'close'
    end
  end

  resources :movies

  devise_for :users, controllers: { registrations: :registrations }

  root 'application#index'

  get 'admin' => 'application#admin'

  resources :users, only: [:index, :show, :destroy, :update]

  get 'invite' => 'invitation#index'
  post 'invite/email' => 'invitation#for_email'
  get 'invite/link' => 'invitation#generate_link'

  resources :votes, only: [:index, :create, :destroy] do
    member do
      post :up, :down
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :invitation
  belongs_to :user
  has_many :referrals, :foreign_key => 'user_id', :class_name => "User"

  def admin?
    self.role == 'admin'
  end

  def approved?
    not self.user.nil?
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else
      super
    end
  end

  def self.statistics
    %w(
      email
      sign_in_count
      current_sign_in_at
      last_sign_in_at
      last_sign_in_ip
      current_sign_in_ip
      created_at
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_admin

  def index
  end

  def show
    @user = User.find id_param
  end

  def destroy
    user = User.find(id_param)
    case
      when user == current_user
        flash[:error] = "Cannot destroy youself!"
        redirect_to user_path(id_param)
      when user.admin?
        flash[:error] = "Cannot destroy fellow admin!"
        redirect_to user_path(id_param)
      else
        @user = User.destroy id_param
    end
  end

  def update
    @query = query_param.to_sym
    @user = User.find(id_param).tap do |user|
      case @query
      when :approve
        user.user = current_user
      when :promote
        user.role = 'admin'
      end
      user.save!
    end
  end

  private

  def id_param
    params.require(:id)
  end

  def query_param
    params.permit(:query)[:query] || 'approve'
  end
end

app/views/user/user.html.haml
.form
  %p#notice= notice
  %table
    %tr
      %td
        %strong Name :
      %td
        = @user.name
    %tr
      %td
        %strong Email :
      %td
        = @user.email
    %tr
      %td
        %strong Seen times :
      %td
        =  @user.sign_in_count
    %tr
      %td
        %strong Current login :
      %td
        =  @user.current_sign_in_at
    %tr
      %td
        %strong Last login :
      %td
        =  @user.last_sign_in_at
    %tr
      %td
        %strong Last IP :
      %td
        =  @user.last_sign_in_ip
    %tr
      %td
        %strong Current IP :
      %td
        =  @user.current_sign_in_ip
    %tr
      %td
        %strong Created at :
      %td
        =  @user.created_at
    %tr
      %td
        %strong Role :
      %td
        =  @user.role
  \#{link_to 'Back', users_path}

app/views/user/users.html.haml
%h1 Listing users
%table
  %thead
    %tr
      %th Email
      %th Name
      %th Approved By
      %th{:colspan => "2"}
  %tbody
    - User.find_each do |user|
      %tr
        %td= user.email
        %td= user.name
        %td= user.user.nil? ? link_to("Approve", "") : (user.user.name || user.user_id)
        %td= link_to 'Show', user_show_path(user)
        %td= link_to 'Destroy', user_show_path(user), method: :delete, data: { confirm: 'Are you sure?' }