config/routes.rb
Rails.application.routes.draw do

  default_url_options Rails.application.config.action_mailer.default_url_options

  resources :events do
    member do
      post 'close'
    end
  end

  resources :movies

  devise_for :users, controllers: { registrations: :registrations }

  root 'application#index'

  get 'admin' => 'application#admin'

  resources :users, only: [:index, :show, :destroy, :update]

  get 'invite' => 'invitation#index'
  post 'invite/email' => 'invitation#for_email'
  get 'invite/link' => 'invitation#generate_link'

  resources :votes, only: [:index, :create, :destroy] do
    member do
      post :up, :down
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found
  before_action :check_admin, only: :admin

  def index
  end

  def admin
  end

  protected
  def check_user
    redirect_to new_user_registration_path unless user_signed_in?
  end

  def check_admin
    unless current_user.try :admin?
      flash[:error] = "Only admin can do that!"
      redirect_to root_path
    end
  end

  def record_not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/admin.html.haml
.cards
  .card
    .card-image
    = link_to(events_path) do
      .card-header Events
      .card-copy
        %p Tools for event management.
      .card-stats
        %ul
          %li
            %i.fa.fa-calendar-o.fa-2x
          %li
            = pluralize(Event.find_each.size, "event")
            %span
              in database
  .card
    .card-image
    = link_to(movies_path) do
      .card-header Movies
      .card-copy
        %p Tools for movies management.
      .card-stats
        %ul
          %li
            %i.fa.fa-video-camera.fa-2x
          %li
            = pluralize(Movie.find_each.size, "movie")
            %span
              in database
  .card
    .card-image
    = link_to(users_path) do
      .card-header Users
      .card-copy
        %p Tools for user management.
      .card-stats
        %ul
          %li
            %i.fa.fa-users.fa-2x
          %li
            = pluralize(User.find_each.size, "user")
            %span
              in database

app/views/application/index.html.haml
.grid-items
  - if user_signed_in?
    = link_to movies_path, class: "grid-item" do
      %h1 Movies
      %p Add new movies
      %i.fa.fa-video-camera.fa-4x.logo
    = link_to votes_path, class: ['grid-item', 'grid-item-big', 'grid-item-image'] do
      %h1 Votes
      %p Vote for next event!
      %i.fa.fa-thumbs-o-up.fa-4x.logo
    = link_to events_path, class: ['grid-item', 'grid-item-big'] do
      %h1 Events
      %p Things we've done so far
      %i.fa.fa-calendar-o.fa-4x.logo
    = link_to invite_path, class: 'grid-item' do
      %h1 Invite friend
      %p Have a friend? Invite him!
      %i.fa.fa-user-plus.fa-4x.logo
    - if current_user.try :admin?
      = link_to admin_path, class: ['grid-item', 'grid-item-full'] do
        %h1 Admin tools
        %p Create, edit and destroy users, events, movies and votes.
        %i.fa.fa-connectdevelop.fa-4x.logo
  - else
    #map-canvas